### ISSUE TITLE
lin-cms-dotnetcore 计划处理问题

### ISSUE THREAD

**Issue by luoyunchong** [luoyunchong/lin-cms-dotnetcore#6]
### 0.3.0系统权限模块更新
1. lin_permission  权限表，本系统通过反射在系统初次启动时，启动异步任务，将不存在的权限新增到此表中。
2. lin_group_permission  分组权限表，用于分组与权限表的关联
3. lin_user_group  用户分组表。用于用户和分组表的关联。可配置一个用户属于多个分组。
4. lin_user_identity 用户授权信息表，用于存储不同登录类型的用户信息，如用户名、第三方应用快速登录（微信、QQ、GitHub、Gitee）的登录

完整的表结构文档: https://igeekfan.gitee.io/vovo-docs/dotnetcore/lin-cms/table.html

**Comment by luoyunchong** [comment]
## 特性
- [.Net Core结合AspNetCoreRateLimit实现限流](https://www.cnblogs.com/EminemJK/p/12720691.html)
- 方法级别权限控制
- 社交账号管理：支持多种第三社交账号登录，不干涉原用户数据，实现第三方账号管理
- 多语言

**Comment by luoyunchong** [comment]
1.github快速登录的BUG
主要是docker部署后，然后通过nginx反向代理，配置 ssl,但request.Scheme得到的还是http,而不是https。
2. qq快速登录，主要是申请时，选的回调域名是 https://api.igeekfan.cn/
3. 文章评论中：回复别人后，关闭回复状态。
4. 事务问题:有时还是会提示（嵌套性事务，异步（必须加await））
[11:37:19 ERR] Connection id "0HLVN2V9CD1C8", Request id "0HLVN2V9CD1C8:00000001": An unhandled exception was thrown by the application. <s:Microsoft.AspNetCore.Server.Kestrel>

System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at FreeSql.UnitOfWorkManager.Dispose()
   at Autofac.Core.Disposer.DisposeAsync(Boolean disposing)
   at Autofac.Core.Lifetime.LifetimeScope.DisposeAsync(Boolean disposing)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.DisposeAsync()
   at Autofac.Extensions.DependencyInjection.AutofacServiceScope.DisposeAsync()
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
atMicrosoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FireOnCompletedAwaited(Task currentTask, Stack`1 onCompleted)


5. 评论增加emoji选择，文章支持表情等字符
6. 支持富文本编辑器。
（已做）
7. 用户关闭评论时，无法对随笔进行评论

**Comment by luoyunchong** [comment]
- [ ] 注册功能增强，验证用户邮件，可根据邮件找回密码。
- [ ] 消息实时推送，用户点赞，评论后，用户在线，则直接推送消息
- [ ] 权限列表，显示后台路由
